create table auth_email_verification_codes (
    id bigint generated by default as identity primary key,
    email varchar(320) not null,
    purpose varchar(32) not null,
    code_hash varchar(128) not null,
    expires_at timestamp not null,
    consumed_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint chk_auth_email_verification_codes_purpose check (purpose in ('REGISTER'))
);

create index idx_auth_email_verification_codes_email_purpose
    on auth_email_verification_codes (email, purpose, created_at);

create index idx_auth_email_verification_codes_expires_at
    on auth_email_verification_codes (expires_at);
