create table patch_versions (
    id bigint generated by default as identity primary key,
    patch_key varchar(32) not null unique,
    ddragon_version varchar(64) not null,
    game_version varchar(64),
    release_date date,
    source_status varchar(32) not null,
    detected_at timestamp not null,
    published_at timestamp,
    checksum varchar(128),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create index idx_patch_versions_status on patch_versions (source_status);
create index idx_patch_versions_published_at on patch_versions (published_at);

create table patch_source_documents (
    id bigint generated by default as identity primary key,
    patch_version_id bigint not null,
    source_type varchar(64) not null,
    locale varchar(16) not null,
    title varchar(255) not null,
    source_url varchar(1024),
    raw_content text,
    content_hash varchar(128) not null,
    fetched_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint fk_patch_source_documents_patch foreign key (patch_version_id) references patch_versions(id)
);

create index idx_patch_source_documents_patch on patch_source_documents (patch_version_id);
create index idx_patch_source_documents_hash on patch_source_documents (content_hash);

create table patch_changes (
    id bigint generated by default as identity primary key,
    patch_version_id bigint not null,
    target_type varchar(64) not null,
    target_key varchar(64) not null,
    target_name varchar(128),
    change_type varchar(64) not null,
    field varchar(128),
    before_value text,
    after_value text,
    summary_zh text,
    summary_en text,
    confidence decimal(5,4) not null default 0,
    source_document_id bigint,
    reviewed_by varchar(128),
    reviewed_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint fk_patch_changes_patch foreign key (patch_version_id) references patch_versions(id),
    constraint fk_patch_changes_source foreign key (source_document_id) references patch_source_documents(id)
);

create index idx_patch_changes_patch on patch_changes (patch_version_id);
create index idx_patch_changes_target on patch_changes (target_type, target_key);
create index idx_patch_changes_source on patch_changes (source_document_id);

create table cn_meta_snapshots (
    id bigint generated by default as identity primary key,
    source varchar(64) not null,
    patch_key varchar(32) not null,
    queue_id integer not null,
    tier_scope varchar(64) not null,
    role varchar(32) not null,
    data_date date not null,
    captured_at timestamp not null,
    source_url varchar(1024),
    content_hash varchar(128) not null,
    status varchar(32) not null,
    created_at timestamp not null default current_timestamp
);

create index idx_cn_meta_snapshots_lookup on cn_meta_snapshots (patch_key, queue_id, tier_scope, role);
create index idx_cn_meta_snapshots_hash on cn_meta_snapshots (content_hash);

create table cn_champion_stats (
    id bigint generated by default as identity primary key,
    snapshot_id bigint not null,
    champion_id integer not null,
    role varchar(32) not null,
    tier_scope varchar(64) not null,
    win_rate decimal(7,4),
    pick_rate decimal(7,4),
    ban_rate decimal(7,4),
    avg_kda decimal(7,2),
    avg_gold decimal(10,2),
    avg_damage_share decimal(7,4),
    avg_damage_taken_share decimal(7,4),
    rank_index integer,
    sample_note varchar(255),
    created_at timestamp not null default current_timestamp,
    constraint fk_cn_champion_stats_snapshot foreign key (snapshot_id) references cn_meta_snapshots(id)
);

create index idx_cn_champion_stats_lookup on cn_champion_stats (champion_id, role, tier_scope);
create index idx_cn_champion_stats_snapshot on cn_champion_stats (snapshot_id);

create table cn_champion_builds (
    id bigint generated by default as identity primary key,
    snapshot_id bigint not null,
    champion_id integer not null,
    role varchar(32) not null,
    tier_scope varchar(64) not null,
    item_build_json text,
    rune_build_json text,
    skill_order varchar(128),
    summoner_spells_json text,
    popularity decimal(7,4),
    win_rate decimal(7,4),
    created_at timestamp not null default current_timestamp,
    constraint fk_cn_champion_builds_snapshot foreign key (snapshot_id) references cn_meta_snapshots(id)
);

create index idx_cn_champion_builds_lookup on cn_champion_builds (champion_id, role, tier_scope);
create index idx_cn_champion_builds_snapshot on cn_champion_builds (snapshot_id);

create table lpl_matches (
    id bigint generated by default as identity primary key,
    bmid varchar(128) not null,
    tournament varchar(128) not null,
    split varchar(64),
    match_date date not null,
    team_blue varchar(128) not null,
    team_red varchar(128) not null,
    source_url varchar(1024),
    captured_at timestamp not null,
    created_at timestamp not null default current_timestamp
);

create index idx_lpl_matches_bmid on lpl_matches (bmid);
create index idx_lpl_matches_date on lpl_matches (match_date);

create table lpl_games (
    id bigint generated by default as identity primary key,
    match_id bigint not null,
    game_number integer not null,
    patch_key varchar(32) not null,
    duration_seconds integer,
    winner_side varchar(16),
    created_at timestamp not null default current_timestamp,
    constraint fk_lpl_games_match foreign key (match_id) references lpl_matches(id)
);

create index idx_lpl_games_match on lpl_games (match_id);
create index idx_lpl_games_patch on lpl_games (patch_key);

create table lpl_pick_bans (
    id bigint generated by default as identity primary key,
    game_id bigint not null,
    phase varchar(32) not null,
    side varchar(16) not null,
    champion_id integer not null,
    team varchar(128),
    player_name varchar(128),
    role varchar(32),
    created_at timestamp not null default current_timestamp,
    constraint fk_lpl_pick_bans_game foreign key (game_id) references lpl_games(id)
);

create index idx_lpl_pick_bans_game on lpl_pick_bans (game_id);
create index idx_lpl_pick_bans_champion on lpl_pick_bans (champion_id, role);

create table lpl_player_game_stats (
    id bigint generated by default as identity primary key,
    game_id bigint not null,
    player_name varchar(128) not null,
    team varchar(128) not null,
    role varchar(32) not null,
    champion_id integer not null,
    kills integer not null default 0,
    deaths integer not null default 0,
    assists integer not null default 0,
    cs integer not null default 0,
    gold integer not null default 0,
    damage integer not null default 0,
    items_json text,
    runes_json text,
    created_at timestamp not null default current_timestamp,
    constraint fk_lpl_player_stats_game foreign key (game_id) references lpl_games(id)
);

create index idx_lpl_player_stats_game on lpl_player_game_stats (game_id);
create index idx_lpl_player_stats_lookup on lpl_player_game_stats (champion_id, role);

create table playstyle_cards (
    id bigint generated by default as identity primary key,
    patch_key varchar(32) not null,
    champion_id integer not null,
    role varchar(32) not null,
    title varchar(255) not null,
    card_type varchar(64) not null,
    summary text not null,
    when_to_use text,
    when_not_to_use text,
    core_items_json text,
    runes_json text,
    skill_order varchar(128),
    source_tier varchar(64) not null,
    confidence decimal(5,4) not null default 0,
    freshness_status varchar(32) not null,
    status varchar(32) not null,
    expires_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create index idx_playstyle_cards_lookup on playstyle_cards (patch_key, champion_id, role);
create index idx_playstyle_cards_status on playstyle_cards (status, freshness_status);

create table playstyle_card_sources (
    id bigint generated by default as identity primary key,
    card_id bigint not null,
    source_name varchar(128) not null,
    source_url varchar(1024),
    source_type varchar(64) not null,
    observed_at timestamp,
    evidence_note text,
    created_at timestamp not null default current_timestamp,
    constraint fk_playstyle_card_sources_card foreign key (card_id) references playstyle_cards(id)
);

create index idx_playstyle_card_sources_card on playstyle_card_sources (card_id);
create index idx_playstyle_card_sources_type on playstyle_card_sources (source_type);

create table patch_relevance_rules (
    id bigint generated by default as identity primary key,
    patch_key varchar(32) not null,
    champion_id integer,
    item_id integer,
    rune_id integer,
    change_type varchar(64) not null,
    invalidates_playstyle_cards boolean not null default false,
    note text,
    created_at timestamp not null default current_timestamp
);

create index idx_patch_relevance_rules_patch on patch_relevance_rules (patch_key);
create index idx_patch_relevance_rules_champion on patch_relevance_rules (champion_id);
create index idx_patch_relevance_rules_item on patch_relevance_rules (item_id);
create index idx_patch_relevance_rules_rune on patch_relevance_rules (rune_id);
