create table users (
    id bigint generated by default as identity primary key,
    email varchar(320) not null,
    display_name varchar(64),
    password_hash varchar(255) not null,
    status varchar(32) not null default 'ACTIVE',
    role varchar(32) not null default 'USER',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    last_login_at timestamp,
    constraint uq_users_email unique (email),
    constraint chk_users_status check (status in ('ACTIVE', 'DISABLED')),
    constraint chk_users_role check (role in ('USER', 'ADMIN'))
);

create index idx_users_status on users (status);

create table auth_refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(128) not null,
    expires_at timestamp not null,
    revoked_at timestamp,
    created_at timestamp not null default current_timestamp,
    last_used_at timestamp,
    user_agent varchar(512),
    constraint uq_auth_refresh_tokens_hash unique (token_hash),
    constraint fk_auth_refresh_tokens_user foreign key (user_id) references users(id)
);

create index idx_auth_refresh_tokens_user on auth_refresh_tokens (user_id);
create index idx_auth_refresh_tokens_expires_at on auth_refresh_tokens (expires_at);
