create table cn_meta_sync_jobs (
    id bigint generated by default as identity primary key,
    source varchar(64) not null,
    patch_key varchar(32) not null,
    queue_id integer not null,
    tier_scope varchar(64) not null,
    role varchar(32) not null,
    status varchar(32) not null,
    started_at timestamp not null,
    finished_at timestamp,
    error_message text,
    request_count integer not null default 0,
    row_count integer not null default 0,
    content_hash varchar(128),
    created_at timestamp not null default current_timestamp
);

create index idx_cn_meta_sync_jobs_lookup
    on cn_meta_sync_jobs (source, patch_key, queue_id, tier_scope, role, started_at);
create index idx_cn_meta_sync_jobs_content_hash on cn_meta_sync_jobs (content_hash);
create index idx_cn_meta_sync_jobs_status on cn_meta_sync_jobs (status, started_at);

create table cn_meta_source_documents (
    id bigint generated by default as identity primary key,
    sync_job_id bigint not null,
    source varchar(64) not null,
    source_url varchar(1024),
    request_key varchar(255) not null,
    http_status integer,
    raw_content text,
    content_hash varchar(128) not null,
    fetched_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_cn_meta_source_documents_job foreign key (sync_job_id) references cn_meta_sync_jobs(id)
);

create index idx_cn_meta_source_documents_job on cn_meta_source_documents (sync_job_id);
create index idx_cn_meta_source_documents_hash on cn_meta_source_documents (content_hash);
create index idx_cn_meta_source_documents_request on cn_meta_source_documents (source, request_key);
