create table opgg_champion_detail_cache (
    id bigint generated by default as identity primary key,
    mode varchar(32) not null,
    region varchar(16) not null,
    tier varchar(32) not null,
    position varchar(32) not null,
    champion_id integer not null,
    cache_date date not null,
    source_version varchar(64),
    detail_json text not null,
    fetched_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uq_opgg_champion_detail_cache unique (
        mode, region, tier, position, champion_id, cache_date
    )
);

create index idx_opgg_champion_detail_cache_lookup
    on opgg_champion_detail_cache (mode, region, tier, position, champion_id, cache_date);

create index idx_opgg_champion_detail_cache_date
    on opgg_champion_detail_cache (cache_date);
