create table opgg_champion_list_cache (
    id bigint generated by default as identity primary key,
    mode varchar(32) not null,
    region varchar(16) not null,
    tier varchar(32) not null,
    cache_date date not null,
    source_version varchar(64),
    list_json text not null,
    fetched_at timestamp not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uq_opgg_champion_list_cache unique (
        mode, region, tier, cache_date
    )
);

create index idx_opgg_champion_list_cache_lookup
    on opgg_champion_list_cache (mode, region, tier, cache_date);

create index idx_opgg_champion_list_cache_date
    on opgg_champion_list_cache (cache_date);
