create table user_credit_balances (
    user_id bigint primary key,
    balance integer not null default 0,
    updated_at timestamp not null default current_timestamp,
    constraint fk_user_credit_balances_user foreign key (user_id) references users(id),
    constraint chk_user_credit_balances_non_negative check (balance >= 0)
);

create table credit_ledger_entries (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    actor_user_id bigint,
    entry_type varchar(64) not null,
    amount integer not null,
    balance_after integer not null,
    idempotency_key varchar(128),
    reference_type varchar(64),
    reference_id varchar(128),
    reason varchar(512),
    created_at timestamp not null default current_timestamp,
    constraint fk_credit_ledger_entries_user foreign key (user_id) references users(id),
    constraint fk_credit_ledger_entries_actor foreign key (actor_user_id) references users(id),
    constraint uq_credit_ledger_entries_idempotency unique (user_id, idempotency_key),
    constraint chk_credit_ledger_entries_type check (entry_type in ('ADMIN_ADJUSTMENT', 'AI_CHARGE', 'AI_REFUND')),
    constraint chk_credit_ledger_entries_amount check (amount <> 0),
    constraint chk_credit_ledger_entries_balance_after check (balance_after >= 0)
);

create index idx_credit_ledger_entries_user_created on credit_ledger_entries (user_id, created_at);
create index idx_credit_ledger_entries_actor on credit_ledger_entries (actor_user_id);

create table ai_analysis_runs (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    endpoint varchar(128) not null,
    provider varchar(64) not null,
    model varchar(128) not null,
    status varchar(32) not null,
    idempotency_key varchar(128),
    charged_credits integer not null default 0,
    refunded_credits integer not null default 0,
    prompt_tokens bigint not null default 0,
    completion_tokens bigint not null default 0,
    total_tokens bigint not null default 0,
    error_code varchar(128),
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    completed_at timestamp,
    constraint fk_ai_analysis_runs_user foreign key (user_id) references users(id),
    constraint uq_ai_analysis_runs_idempotency unique (user_id, idempotency_key),
    constraint chk_ai_analysis_runs_status check (status in ('RESERVED', 'SUCCEEDED', 'FAILED', 'REFUNDED')),
    constraint chk_ai_analysis_runs_charged_non_negative check (charged_credits >= 0),
    constraint chk_ai_analysis_runs_refunded_non_negative check (refunded_credits >= 0)
);

create index idx_ai_analysis_runs_user_created on ai_analysis_runs (user_id, created_at);
create index idx_ai_analysis_runs_status on ai_analysis_runs (status);
