create table auth_password_reset_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(128) not null,
    expires_at timestamp not null,
    used_at timestamp,
    created_at timestamp not null default current_timestamp,
    constraint uq_auth_password_reset_tokens_hash unique (token_hash),
    constraint fk_auth_password_reset_tokens_user foreign key (user_id) references users(id)
);

create index idx_auth_password_reset_tokens_user on auth_password_reset_tokens (user_id);
create index idx_auth_password_reset_tokens_expires_at on auth_password_reset_tokens (expires_at);
