import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync(new URL('./RefreshIconButton.vue', import.meta.url), 'utf8')
const refreshButtonStyleBlock = source.match(/\.refresh-icon-btn \{[\s\S]*?\n\}/)?.[0] || ''

test('refresh icon button keeps the shared refresh action state machine', () => {
  assert.match(source, /ariaLabel\?: string/)
  assert.match(source, /loading\?: boolean/)
  assert.match(source, /onActivated/)
  assert.match(source, /onDeactivated/)
  assert.match(source, /const REFRESH_ANIMATION_CYCLE_MS = 800/)
  assert.match(source, /const REFRESH_EDGE_GLOW_RANGE = 96/)
  assert.match(source, /const REFRESH_EDGE_GLOW_MIN = 0\.03/)
  assert.match(source, /const REFRESH_EDGE_GLOW_FALLOFF = 1\.72/)
  assert.match(source, /const externalLoading = computed\(\(\) => props\.loading \|\| props\.busy\)/)
  assert.match(source, /const accessibleLabel = computed\(\(\) => props\.ariaLabel \|\| props\.label \|\| ''\)/)
  assert.match(source, /const isAnimating = ref\(false\)/)
  assert.match(source, /const buttonRef = ref<HTMLButtonElement \| null>\(null\)/)
  assert.match(source, /const isDisabled = computed\(\(\) => props\.disabled \|\| externalLoading\.value \|\| isAnimating\.value\)/)
  assert.match(source, /@pointermove="updateGlow"/)
  assert.match(source, /@pointerleave="updateNearbyGlow"/)
  assert.doesNotMatch(source, /@pointerleave="resetGlow"/)
  assert.match(source, /function attachPointerListener\(\)/)
  assert.match(source, /function detachPointerListener\(\)/)
  assert.match(source, /document\.addEventListener\('pointermove', updateNearbyGlow, \{ capture: true, passive: true \}\)/)
  assert.match(source, /document\.removeEventListener\('pointermove', updateNearbyGlow, true\)/)
  assert.match(source, /onActivated\(attachPointerListener\)/)
  assert.match(source, /onDeactivated\(\(\) => \{[\s\S]*detachPointerListener\(\)[\s\S]*buttonRef\.value && resetGlowElement\(buttonRef\.value\)/)
  assert.match(source, /function updateGlow\(event: PointerEvent\)/)
  assert.match(source, /function updateNearbyGlow\(event: PointerEvent\)/)
  assert.match(source, /const maxStrength = Math\.max\(top, right, bottom, left\)/)
  assert.match(source, /return Math\.pow\(raw, REFRESH_EDGE_GLOW_FALLOFF\)/)
  assert.match(source, /target\.style\.setProperty\('--refresh-glow-opacity', maxStrength\.toFixed\(3\)\)/)
  assert.match(source, /if \(maxStrength > REFRESH_EDGE_GLOW_MIN\) \{[\s\S]*target\.dataset\.nearGlow = 'true'[\s\S]*\} else \{[\s\S]*delete target\.dataset\.nearGlow/)
  assert.match(source, /function resetGlow\(event: PointerEvent \| FocusEvent\)/)
  assert.match(source, /function handleClick\(event: MouseEvent\) \{[\s\S]*startAnimation\(\)[\s\S]*emit\('click', event\)[\s\S]*scheduleStopAfterCurrentCycle\(\)/)
  assert.match(source, /watch\(externalLoading,[\s\S]*startAnimation\(\)[\s\S]*scheduleStopAfterCurrentCycle\(\)/)
})

test('refresh icon button renders a clockwise icon and spinning animation', () => {
  assert.match(source, /class="refresh-icon-btn"/)
  assert.match(source, /class="refresh-icon"[\s\S]*:class="\{ 'is-spinning': isAnimating \}"/)
  assert.match(source, /d="M19\.2 9\.2A7\.6 7\.6 0 1 0 20 13\.4"/)
  assert.match(source, /d="M19\.2 4\.8v4\.4h-4\.4"/)
  assert.match(source, /stroke-width="2\.25"/)
  assert.match(source, /spinnerRef\.value\.animate\(\[[\s\S]*transform: 'rotate\(0deg\)'[\s\S]*transform: 'rotate\(360deg\)'/)
  assert.match(source, /\.refresh-icon \{[\s\S]*transform-origin: 50% 50%[\s\S]*transform-box: view-box/)
  assert.match(source, /\.refresh-icon\.is-spinning \{[\s\S]*animation: rankpeek-refresh-spin var\(--refresh-action-cycle\) linear infinite/)
  assert.match(source, /@keyframes rankpeek-refresh-spin \{[\s\S]*to \{[\s\S]*transform: rotate\(360deg\)/)
})

test('refresh icon button follows the layered design glow contract', () => {
  assert.match(source, /\.refresh-icon-btn \{[\s\S]*--refresh-glow-x: 50%[\s\S]*--refresh-glow-opacity: 0[\s\S]*--refresh-border: rgba\(255, 255, 255, 0\.12\)[\s\S]*--refresh-border-hover: rgba\(92, 181, 255, 0\.62\)[\s\S]*--refresh-local-core: rgba\(78, 215, 255, 0\.98\)[\s\S]*--refresh-local-fade: rgba\(41, 151, 255, 0\.48\)[\s\S]*--refresh-edge-shadow:[\s\S]*--refresh-hover-shadow:/)
  assert.match(source, /border: 1px solid var\(--refresh-border\)/)
  assert.match(source, /background: var\(--refresh-bg\)/)
  assert.match(source, /\.refresh-icon-btn::before \{[\s\S]*radial-gradient\([\s\S]*circle var\(--refresh-edge-size\) at calc\(var\(--refresh-glow-x\) \+ 1px\) calc\(var\(--refresh-glow-y\) \+ 1px\)[\s\S]*var\(--refresh-local-core\) 0%[\s\S]*var\(--refresh-local-fade\) 42%[\s\S]*mask-composite: exclude/)
  assert.match(source, /\.refresh-icon-btn:hover:not\(:disabled\)::before,[\s\S]*\.refresh-icon-btn\[data-near-glow='true'\]:not\(:disabled\)::before \{[\s\S]*opacity: var\(--refresh-glow-opacity\)/)
  assert.match(source, /\.refresh-icon-btn:focus-visible::before \{[\s\S]*opacity: 1/)
  assert.match(source, /--refresh-edge-size: 86px/)
  assert.match(source, /\.refresh-icon-btn:hover:not\(:disabled\) \{[\s\S]*border-color: var\(--refresh-border-hover\)[\s\S]*background: var\(--refresh-bg-hover\)[\s\S]*box-shadow:[\s\S]*var\(--refresh-hover-shadow\),[\s\S]*var\(--refresh-edge-shadow\)/)
  assert.match(source, /\.refresh-icon-btn\[data-near-glow='true'\]:not\(:hover\):not\(:focus-visible\):not\(:disabled\) \{[\s\S]*border-color: var\(--refresh-border\)[\s\S]*box-shadow: var\(--refresh-edge-shadow\)/)
  assert.doesNotMatch(source, /0 0 22px rgba\(92, 163, 234, calc\(var\(--refresh-glow-opacity\) \* 0\.46\)\)/)
  assert.match(source, /\.refresh-icon-btn:focus-visible \{[\s\S]*border-color: var\(--refresh-border-focus\)[\s\S]*box-shadow:[\s\S]*var\(--refresh-focus-shadow\),[\s\S]*var\(--refresh-edge-shadow\)/)
  assert.match(source, /\.refresh-icon \{[\s\S]*stroke: currentColor/)
  assert.match(source, /:global\(\[data-theme="light"\] \.refresh-icon-btn\) \{[\s\S]*--refresh-local-core: rgba\(78, 215, 255, 0\.98\)[\s\S]*--refresh-local-fade: rgba\(41, 151, 255, 0\.48\)[\s\S]*color: #000 !important/)
  assert.match(source, /:global\(\[data-theme="light"\] \.refresh-icon-btn:hover\) \{[\s\S]*border-color: var\(--refresh-border-hover\)[\s\S]*box-shadow:[\s\S]*var\(--refresh-hover-shadow\),[\s\S]*var\(--refresh-edge-shadow\)[\s\S]*color: #000 !important/)
  assert.match(source, /:global\(\[data-theme="light"\] \.refresh-icon-btn \.refresh-icon\),[\s\S]*:global\(\[data-theme="light"\] \.refresh-icon-btn \.refresh-icon path\) \{[\s\S]*stroke: #000 !important/)
  assert.match(source, /\.refresh-icon-btn:disabled \{[\s\S]*opacity: 0\.45[\s\S]*cursor: not-allowed/)
  assert.doesNotMatch(refreshButtonStyleBlock, /pointer-events:\s*none/)
  assert.doesNotMatch(source, /refresh-arrow/)
})
