import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

const contentUrl = new URL('./CoachSummaryReportContent.vue', import.meta.url)

test('coach summary report content owns the three report sections and chart caps', () => {
  assert.equal(existsSync(contentUrl), true)
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /近 20 局概览/)
  assert.match(source, /数据分析/)
  assert.match(source, /数据总结/)
  assert.doesNotMatch(source, /AI 分析内容/)
  assert.doesNotMatch(source, /AI 总结/)
  assert.doesNotMatch(source, /下一阶段训练重点/)
  assert.equal((source.match(/<section[\s\S]*?class="report-section/g) || []).length, 3)
  assert.match(source, /MAX_REPORT_CHARTS\s*=\s*3/)
  assert.match(source, /placement === 'overview'/)
  assert.match(source, /CoachSummaryChartBlock/)
  assert.doesNotMatch(source, /analysisCharts|summaryCharts/)
  assert.doesNotMatch(source, /placement === 'analysis'|placement === 'summary'/)
})

test('coach summary report analysis section hides champion advice cards', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /analysis-section/)
  assert.match(source, /finding-list/)
  assert.match(source, /finding-item/)
  assert.match(source, /const findings = computed\(\(\) => props\.report\?\.keyFindings \|\| \[\]\)/)
  assert.doesNotMatch(source, /keyFindings\s*\|\|\s*\[\]\)\.slice\(0,\s*2\)/)
  assert.match(source, /findingText\(finding\)/)
  assert.match(source, /finding\.evidence/)
  assert.match(source, /finding\.reasoning/)
  assert.doesNotMatch(source, /finding\.advice\s*\|\|\s*finding\.reasoning\s*\|\|\s*finding\.evidence/)
  assert.doesNotMatch(source, /<span>\{\{ findings\.length \}\}[^<]*<\/span>/)
  assert.doesNotMatch(source, /championAdvice/)
  assert.doesNotMatch(source, /advice-list/)
  assert.doesNotMatch(source, /advice-item/)
  assert.doesNotMatch(source, /advice\.championName|advice\.role|advice\.reason/)
  assert.doesNotMatch(source, /counter-increment:\s*report-item/)
  assert.doesNotMatch(source, /counter\(report-item/)
})

test('coach summary report summary section hides verdict label and score paper', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /summary-section/)
  assert.match(source, /closingSummary/)
  assert.match(source, /<p class="final-summary ai-report-prose">\{\{ closingSummary \}\}<\/p>/)
  assert.doesNotMatch(source, /verdict-paper/)
  assert.doesNotMatch(source, /report\.verdict\.label/)
  assert.doesNotMatch(source, /formatNumber\(report\.verdict\.score\)/)
  assert.doesNotMatch(source, /<span>\{\{ report\.verdict\.label \}\}<\/span>/)
})

test('coach summary report content uses paper sections instead of nested dashboard cards', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /report-divider|paper-divider|section-divider/)
  assert.match(source, /<section[\s\S]*?class="report-section/)
  assert.doesNotMatch(source, /overview-summary-panel|hero-win-rate-panel/)
  assert.doesNotMatch(source, /finding-card|advice-card|training-card|verdict-card|verdict-paper/)
  assert.doesNotMatch(source, /\.report-section\s*\{[^}]*border:/)
  assert.doesNotMatch(source, /\.report-section\s*\{[^}]*box-shadow:/)
})

test('coach summary report overview keeps facts and hero win-rate figure', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /roleSummary/)
  assert.match(source, /formatRoleLabel/)
  assert.match(source, /heroWinRateStats/)
  assert.match(source, /overview-facts/)
  assert.match(source, /overview-fact-row/)
  assert.match(source, /fact-main/)
  assert.match(source, /fact-sub/)
  assert.match(source, /hero-win-rate-figure/)
  assert.match(source, /hero-win-rate-chart/)
  assert.match(source, /hero-win-rate-y-axis/)
  assert.match(source, />100%<\/span>/)
  assert.match(source, />50%<\/span>/)
  assert.match(source, />0%<\/span>/)
  assert.match(source, /hero-win-rate-x-axis/)
  assert.match(source, /hero-win-rate-avatar/)
  assert.match(source, /:src="heroIcon\(hero\)"/)
  assert.match(source, /COACH_SUMMARY_HERO_ICON_FALLBACK_IDS/)
  assert.match(source, /heroIconChampionId\(hero\)/)
  assert.match(source, /heroDetailLine\(hero\)/)
  assert.match(source, /hero\.championCanonicalName/)
  assert.match(source, /hero\.championDisplayName/)
  assert.doesNotMatch(source, />\s*胜率\s*</)
  assert.doesNotMatch(source, />\s*游玩位置\s*</)
  assert.doesNotMatch(source, />\s*最近游玩英雄\s*</)
  assert.doesNotMatch(source, />\s*主玩英雄胜率\s*</)
  assert.doesNotMatch(source, /柱高对应英雄胜率，颜色按 0-100% 全局刻度映射。/)
})

test('coach summary report overview can switch from hero win-rate to RP index line chart', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /import \{ computed, ref \} from 'vue'/)
  assert.match(source, /activeOverviewChart\s*=\s*ref<'winRate' \| 'rpIndex'>\('winRate'\)/)
  assert.match(source, /rpTrendPoints/)
  assert.match(source, /visibleOverviewChart/)
  assert.match(source, /rp-index-layout/)
  assert.match(source, /v-if="visibleOverviewChart !== 'rpIndex'"/)
  assert.match(source, /rp-index-wide/)
  assert.match(source, /normalizeOverviewSummaryText/)
  assert.match(source, /overview-chart-control-row/)
  assert.match(source, /overview-chart-tabs/)
  assert.match(source, /class="overview-chart-control-row"[\s\S]*class="rp-index-hover-zone"[\s\S]*class="overview-chart-tabs"/)
  assert.match(source, />英雄胜率<\/button>/)
  assert.match(source, />RP指数曲线<\/button>/)
  assert.match(source, /activeOverviewChart = 'winRate'/)
  assert.match(source, /activeOverviewChart = 'rpIndex'/)
  assert.match(source, /class="rp-index-figure"/)
  assert.match(source, /class="rp-index-chart"/)
  assert.match(source, /viewBox="0 0 760 280"/)
  assert.match(source, /aria-label="近 20 局 RP指数曲线"/)
  assert.match(source, /rp-index-polyline/)
  assert.match(source, /rp-index-point/)
  assert.match(source, /rp-index-hover-panel/)
  assert.match(source, /rp-index-hover-zone/)
  assert.match(source, /formatRpChartPointLabel\(point\)/)
  assert.match(source, /formatRpHoverSummary\(activeRpChartPoint\)/)
  assert.match(source, /formatRpKdaText\(point\)/)
  assert.match(source, /rpPointResultClass\(point\)/)
  assert.match(source, /match\s*=\s*raw\.match\(\//)
  assert.match(source, /return match\[1\]\.replace\(/)
  assert.match(source, /function extractOverviewSummaryMetrics/)
  assert.match(source, /function removeRepeatedOverviewMetrics/)
  assert.match(source, /function removeLocalOverallStateText/)
  assert.match(source, /整体状态/)
  assert.match(source, /getChampionIconUrl\(point\.championId\)/)
  assert.match(source, /\.rp-index-chart\s*\{[\s\S]*min-height:\s*240px/)
  assert.match(source, /\.hero-win-rate-figure\.rp-index-wide\s*\{[\s\S]*min-height:\s*390px/)
  assert.match(source, /\.hero-win-rate-figure\.rp-index-wide \.rp-index-chart,[\s\S]*min-height:\s*340px/)
  assert.match(source, /\.overview-chart-control-row\s*\{[\s\S]*justify-content:\s*flex-end/)
  assert.match(source, /\.overview-chart-tabs button\s*\{[\s\S]*min-height:\s*36px/)
  assert.match(source, /\.rp-index-hover-zone\s*\{[\s\S]*height:\s*42px/)
  assert.match(source, /\.rp-index-hover-zone\s*\{[\s\S]*justify-content:\s*flex-start/)
  assert.match(source, /\.rp-index-hover-panel\s*\{[\s\S]*position:\s*static/)
  assert.match(source, /\.rp-index-hover-panel\s*\{[\s\S]*height:\s*42px/)
  assert.match(source, /\.rp-index-hover-panel span\s*\{[\s\S]*font-size:\s*15px/)
  assert.doesNotMatch(source, /\.rp-index-hover-panel\s*\{[\s\S]*bottom:\s*10px/)
  assert.match(source, /\.rp-index-polyline\s*\{[\s\S]*stroke:\s*#4d9dff/)
  assert.match(source, /\.rp-index-point-ring\.result-win\s*\{[\s\S]*stroke:\s*#4d9dff/)
  assert.match(source, /\.rp-index-point-ring\.result-loss\s*\{[\s\S]*stroke:\s*#ff5c7a/)
  assert.doesNotMatch(source, /echarts|chart\.js|highcharts|d3/i)
})

test('coach summary report hero win-rate axis uses quarter ticks and grid lines', () => {
  const source = readFileSync(contentUrl, 'utf8')
  const yAxis = source.match(/<div class="hero-win-rate-y-axis"[\s\S]*?<\/div>/)?.[0] || ''
  const grid = source.match(/<div class="hero-win-rate-grid"[\s\S]*?<\/div>/)?.[0] || ''

  for (const tick of ['100', '75', '50', '25', '0']) {
    assert.match(yAxis, new RegExp(`>${tick}%<\\/span>`))
  }
  assert.equal((yAxis.match(/<span>/g) || []).length, 5)
  assert.equal((grid.match(/<span><\/span>/g) || []).length, 5)
  assert.doesNotMatch(source, /echarts|chart\.js/i)
})

test('coach summary report overview aligns fact rows and chart bottoms', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /--overview-bottom-gap/)
  assert.match(source, /\.overview-layout\s*\{[\s\S]*align-items:\s*stretch/)
  assert.match(source, /\.overview-layout\s*\{[\s\S]*padding-bottom:\s*var\(--overview-bottom-gap\)/)
  assert.match(source, /\.overview-text-column\s*\{[\s\S]*padding-bottom:\s*var\(--overview-bottom-gap\)/)
  assert.match(source, /\.hero-win-rate-figure\s*\{[\s\S]*height:\s*100%/)
  assert.match(source, /\.hero-win-rate-figure\s*\{[\s\S]*display:\s*flex/)
  assert.match(source, /\.hero-win-rate-figure\s*\{[\s\S]*flex-direction:\s*column/)
  assert.match(source, /\.hero-win-rate-figure\s*\{[\s\S]*padding-bottom:\s*var\(--overview-bottom-gap\)/)
  assert.match(source, /\.hero-win-rate-chart\s*\{[\s\S]*flex:\s*1/)
  assert.match(source, /\.hero-win-rate-chart\s*\{[\s\S]*height:\s*100%/)
  assert.match(source, /\.hero-win-rate-plot\s*\{[\s\S]*height:\s*100%/)
  assert.match(source, /\.hero-win-rate-x-axis\s*\{[\s\S]*margin-top:\s*auto/)
  assert.match(source, /\.overview-fact-row\s*\{[^}]*min-height:/)
  assert.match(source, /\.overview-fact-row\s*\{[^}]*align-items:\s*center/)
  assert.match(source, /\.overview-fact-row\s*\{[^}]*padding:/)
})

test('coach summary report hero win-rate bars are rectangular and reveal values on hover or focus only', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /hero-win-bar-plot/)
  assert.match(source, /hero-win-bar-fill/)
  assert.match(source, /hero-win-tooltip/)
  assert.match(source, /hero-win-rate-games/)
  assert.match(source, /formatHeroChartLabel\(hero\)/)
  assert.match(source, /class="hero-win-rate-column"[\s\S]*:style="\{ '--hero-win-rate': `\$\{clampPercent\(hero\.winRate\)\}%` \}"/)
  assert.match(source, /:aria-label="formatHeroChartLabel\(hero\)"/)
  assert.match(source, /:title="formatHeroChartLabel\(hero\)"/)
  assert.match(source, /\.hero-win-bar-fill\s*\{[\s\S]*height:\s*var\(--hero-win-rate\)/)
  assert.match(source, /\.hero-win-bar-fill\s*\{[\s\S]*border-radius:\s*0/)
  assert.match(source, /\.hero-win-bar-fill\s*\{[\s\S]*background:\s*(?:#[0-9a-fA-F]{3,6}|rgb|rgba|linear-gradient)/)
  assert.match(source, /\.hero-win-tooltip\s*\{[\s\S]*opacity:\s*0/)
  assert.match(source, /\.hero-win-tooltip\s*\{[\s\S]*visibility:\s*hidden/)
  assert.match(source, /\.hero-win-tooltip\s*\{[\s\S]*bottom:\s*(?:min\()?calc\(var\(--hero-win-rate\)/)
  assert.match(source, /\.hero-win-rate-column:hover\s+\.hero-win-tooltip/)
  assert.match(source, /\.hero-win-rate-column:focus(?:-within)?\s+\.hero-win-tooltip/)
  assert.match(source, /tabindex="0"/)
  assert.match(source, /<span class="hero-win-tooltip">[\s\S]*\{\{ formatPercent\(hero\.winRate\) \}\}[\s\S]*\{\{ hero\.games \}\} 场[\s\S]*<\/span>/)
  assert.match(source, /<span class="hero-win-rate-games">\{\{ hero\.games \}\} 场<\/span>/)
  assert.doesNotMatch(source, /<div class="hero-win-rate-x-axis">[\s\S]*hero-win-tooltip[\s\S]*<\/div>/)
  assert.doesNotMatch(source, /hero-win-rate-value/)
  assert.doesNotMatch(source, /hero-win-bar-gradient/)
  assert.doesNotMatch(source, /--hero-win-rate-percent/)
  assert.doesNotMatch(source, /clip-path:\s*inset/)
  assert.doesNotMatch(source, /\.hero-win-bar-plot\s*\{[^}]*border:/)
  assert.doesNotMatch(source, /\.hero-win-bar-plot\s*\{[^}]*background:/)
  assert.doesNotMatch(source, /\.hero-win-rate-track\s*\{[\s\S]*border:/)
  assert.doesNotMatch(source, /\.hero-win-rate-track\s*\{[\s\S]*background:/)
})

test('coach summary report increases information density and prose readability', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /heroDetailLine\(hero\)/)
  assert.match(source, /heroRecordText/)
  assert.match(source, /heroAverageKdaText/)
  assert.match(source, /hero\.wins/)
  assert.match(source, /hero\.losses/)
  assert.match(source, /hero\.averageKda/)
  assert.match(source, /\.section-heading h2\s*\{[\s\S]*font-size:\s*28px/)
  assert.match(source, /\.section-summary,\s*\n\.final-summary\s*\{[\s\S]*font-size:\s*24px/)
  assert.match(source, /\.finding-copy\s*\{[\s\S]*font-size:\s*24px/)
  assert.doesNotMatch(source, /\.fact-sub,\s*\n\.hero-main p,\s*\n\.hero-metrics span,\s*\n\.finding-item p\s*\{/)
  assert.match(source, /\.hero-main h3\s*\{[\s\S]*font-size:\s*15px/)
  assert.match(source, /\.hero-main p\s*\{[\s\S]*font-size:\s*13px/)
  assert.match(source, /\.hero-metrics span\s*\{[\s\S]*font-size:\s*13px/)
  assert.match(source, /\.hero-win-tooltip strong\s*\{[\s\S]*font-size:\s*13px/)
  assert.match(source, /\.hero-win-rate-games\s*\{[\s\S]*font-size:\s*12px/)
  assert.match(source, /\.overview-layout\s*\{[\s\S]*gap:\s*18px/)
  assert.match(source, /\.hero-win-rate-chart\s*\{[\s\S]*min-height:\s*240px/)
})

test('coach summary report divider fades smoothly without a hard center block', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /\.paper-divider\s*\{[\s\S]*height:\s*18px/)
  assert.match(source, /\.paper-divider::before\s*\{[\s\S]*rgba\(148, 163, 184, 0\.34\) 50%/)
  assert.match(source, /\.paper-divider::after\s*\{[\s\S]*width:\s*min\(220px, 28%\)/)
  assert.match(source, /\.paper-divider::after\s*\{[\s\S]*rgba\(var\(--accent-rgb\), 0\.42\) 50%/)
  assert.doesNotMatch(source, /\.paper-divider\s*\{[^}]*background:\s*linear-gradient/)
  assert.doesNotMatch(source, /rgba\(248, 192, 74/)
})

test('coach summary report applies serif prose only to AI generated copy', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.match(source, /ai-report-prose/)
  assert.match(source, /\.ai-report-prose\s*\{[\s\S]*"Noto Serif SC"/)
  assert.match(source, /\.ai-report-prose\s*\{[\s\S]*"Source Han Serif SC"/)
  assert.match(source, /\.ai-report-prose\s*\{[\s\S]*"Songti SC"/)
  assert.match(source, /\.ai-report-prose\s*\{[\s\S]*"SimSun"/)
  assert.match(source, /\.ai-report-prose\s*\{[\s\S]*serif/)
  assert.match(source, /<p class="section-summary ai-report-prose">\{\{ overviewSummary \}\}<\/p>/)
  assert.match(source, /<p class="finding-copy ai-report-prose">\{\{ findingText\(finding\) \}\}<\/p>/)
  assert.match(source, /<p class="final-summary ai-report-prose">\{\{ closingSummary \}\}<\/p>/)
  assert.match(source, /\.ai-report-prose\s*\{[\s\S]*white-space:\s*pre-wrap/)
  assert.doesNotMatch(source, /\.section-summary\s*\{[\s\S]*?(?:-webkit-line-clamp|line-clamp|text-overflow|overflow:\s*hidden)[\s\S]*?\}/)
  assert.doesNotMatch(source, /advice\.(championName|role|reason)/)
  assert.doesNotMatch(source, /report\.verdict\.label|report\.verdict\.score/)
  assert.doesNotMatch(source, /<h2 class="ai-report-prose">/)
  assert.doesNotMatch(source, /class="fact-main ai-report-prose"/)
  assert.doesNotMatch(source, /class="hero-win-tooltip ai-report-prose"/)
})

test('coach summary report hides analysis charts and training plan UI', () => {
  const source = readFileSync(contentUrl, 'utf8')

  assert.doesNotMatch(source, /analysisCharts|summaryCharts/)
  assert.doesNotMatch(source, /placement === 'analysis'|placement === 'summary'/)
  assert.doesNotMatch(source, /v-if="analysisCharts\.length"|v-if="summaryCharts\.length"/)
  assert.doesNotMatch(source, /v-for="chart in analysisCharts"|v-for="chart in summaryCharts"/)
  assert.doesNotMatch(source, /trainingPlan|training-list|training-item/)
  assert.doesNotMatch(source, /item\.task|item\.metricToTrack|item\.target|nextGames/)
  assert.doesNotMatch(source, /下一阶段训练重点|接下来/)
})

test('coach summary report content keeps fallbacks while chart block handles empty dataRef and unsupported kinds', () => {
  const source = readFileSync(contentUrl, 'utf8')
  const chart = readFileSync(new URL('./CoachSummaryChartBlock.vue', import.meta.url), 'utf8')

  assert.match(source, /暂不支持该报告类型/)
  assert.match(source, /报告内容暂时无法解析/)
  assert.match(source, /reportLoadState/)
  assert.match(chart, /图表数据待接入/)
  assert.match(chart, /unsupportedChart/)
  assert.doesNotMatch(source + chart, /echarts|chart\.js|highcharts|d3/i)
})
