import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const viewUrl = new URL('./AiAnalysisView.vue', import.meta.url)
const rendererRoot = fileURLToPath(new URL('..', import.meta.url))

function readRendererFile(path: string) {
  return readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
}

function readViewSource() {
  assert.equal(existsSync(viewUrl), true)
  return readFileSync(viewUrl, 'utf8')
}

test('AI report center keeps account-scoped local results and local-snapshot logic without model or backend calls', () => {
  const source = readViewSource()
  const localAiAnalysis = readRendererFile('services/localAiAnalysis.ts')
  const localDatabaseTypes = readRendererFile('types/localDatabase.ts')

  assert.match(source, /import \{ useGameStore \} from '@\/stores\/game'/)
  assert.match(source, /loadLocalAiAnalysisResults/)
  assert.match(source, /buildAccountAnalysisInputSnapshot/)
  assert.match(source, /prepareAnalysisInputSnapshot/)
  assert.match(source, /gameStore\.currentSummoner/)
  assert.match(source, /accountPuuid/)
  assert.match(source, /limit:\s*20/)
  assert.match(source, /offset:\s*0/)
  assert.match(source, /preparedSnapshot\.value = snapshot/)
  assert.match(source, /snapshot\.inputHash/)
  assert.match(localAiAnalysis, /listAnalysisResultsByAccount\(trimmedPuuid,\s*queryOptions\)/)
  assert.match(localDatabaseTypes, /interface AiAnalysisResult[\s\S]*accountPuuid: string[\s\S]*matchId: string \| null/)
  assert.doesNotMatch(source, /apiClient|DeepSeek|Kimi|OpenAI|fetch\(|axios|\/api\/.*ai/i)
  assert.doesNotMatch(source, /saveAnalysisResult|findAnalysisByInputHash|upsertAnalysis/)
  assert.doesNotMatch(source, /SummonerMatchHistoryPanel|MatchDetailModal/)
  assert.doesNotMatch(source, /listAnalysisResultsByAccount\(['"]all|allAccounts|selectedAccountScope/)
})

test('AI report center product copy, recharge copy, sidebar entry, and icon are wired', () => {
  const sidebar = readRendererFile('components/layout/Sidebar.vue')
  const zhCN = readRendererFile('i18n/locales/zh-CN.ts')
  const enUS = readRendererFile('i18n/locales/en-US.ts')
  const iconPath = resolve(rendererRoot, 'assets/icons/nav-ai-spark.svg')

  assert.match(sidebar, /import aiAnalysisIconSvg from '@\/assets\/icons\/nav-ai-spark\.svg\?raw'/)
  assert.match(sidebar, /path:\s*'\/match-history'[\s\S]*path:\s*'\/ai-analysis'[\s\S]*path:\s*'\/settings'/)
  assert.match(sidebar, /\{ path: '\/ai-analysis', iconSvg: aiAnalysisIconSvg, labelKey: 'nav\.aiAnalysis' \}/)
  assert.match(zhCN, /'aiAnalysis\.title': 'AI \u62a5\u544a\u4e2d\u5fc3'/u)
  assert.match(zhCN, /'aiAnalysis\.subtitle': '\u6240\u6709\u62a5\u544a\u90fd\u4f1a\u6309\u8d26\u53f7\u4fdd\u5b58\u5728\u8fd9\u91cc\u3002'/u)
  assert.match(zhCN, /'aiAnalysis\.rankpeekAccountGuest': '\u672a\u767b\u5f55'/u)
  assert.match(zhCN, /'aiAnalysis\.recharge': '\u5145\u503c'/u)
  assert.match(zhCN, /'aiAnalysis\.featurePreGame': '\u8d5b\u524d\u5206\u6790'/u)
  assert.match(zhCN, /'aiAnalysis\.featurePostGame': '\u8d5b\u540e\u590d\u76d8'/u)
  assert.match(zhCN, /'aiAnalysis\.featurePraise': '\u5938\u5938\u673a'/u)
  assert.match(zhCN, /'aiAnalysis\.featureCoach': '\u7535\u5b50\u6559\u7ec3'/u)
  assert.match(zhCN, /'aiAnalysis\.preGamePositioning': '\u5f00\u5c40\u524d\u7684\u961f\u53cb\u4e0e\u5bf9\u624b\u98ce\u9669\u901f\u89c8\u3002'/u)
  assert.match(zhCN, /'aiAnalysis\.postGamePositioning': '\u5355\u5c40\u7ed3\u675f\u540e\u7684\u8868\u73b0\u590d\u76d8\u3002'/u)
  assert.match(zhCN, /'aiAnalysis\.praisePositioning': '\u6253\u5b8c\u5148\u628a\u4f60\u5938\u8212\u670d\u3002'/u)
  assert.match(zhCN, /'aiAnalysis\.coachPositioning': '\u9636\u6bb5\u6027\u7684\u957f\u671f\u8868\u73b0\u603b\u7ed3\u3002'/u)
  assert.match(zhCN, /'aiAnalysis\.historyTitle': '\u5386\u53f2\u62a5\u544a'/u)
  assert.match(zhCN, /'aiAnalysis\.emptyHistoryTitle': '\u6682\u65e0 AI \u62a5\u544a'/u)
  assert.match(enUS, /'aiAnalysis\.title': 'AI Report Center'/)
  assert.match(enUS, /'aiAnalysis\.subtitle': 'All reports are saved here by account.'/)
  assert.match(enUS, /'aiAnalysis\.recharge': 'Recharge'/)
  assert.match(enUS, /'aiAnalysis\.featurePraise': 'Praise Machine'/)
  assert.match(enUS, /'aiAnalysis\.preGamePositioning': 'A fast risk read on teammates and opponents before the match.'/)
  assert.match(enUS, /'aiAnalysis\.postGamePositioning': 'A single-match performance review after the game.'/)
  assert.match(enUS, /'aiAnalysis\.praisePositioning': 'Get praised first after a match.'/)
  assert.match(enUS, /'aiAnalysis\.coachPositioning': 'A periodic summary of long-term performance.'/)
  assert.doesNotMatch(zhCN, /'aiAnalysis\.featureTitle': '\u0041\u0049 \u529f\u80fd\u5165\u53e3'/u)
  assert.doesNotMatch(zhCN, /'aiAnalysis\.dataPrepTitle':|'aiAnalysis\.serverAiTitle':|'aiAnalysis\.serverAiPhase':/)
  assert.doesNotMatch(zhCN, /'aiAnalysis\.localMatches':|'aiAnalysis\.localDetails':|'aiAnalysis\.checkLocalData':|'aiAnalysis\.inputHash':/)
  assert.doesNotMatch(zhCN, /'aiAnalysis\.preGameDescription':|'aiAnalysis\.postGameDescription':|'aiAnalysis\.praiseDescription':|'aiAnalysis\.coachDescription':/)
  assert.doesNotMatch(zhCN, /'aiAnalysis\.tagShareable':|'aiAnalysis\.tagWeeklyMonthly':/)
  assert.doesNotMatch(zhCN, /\u62a5\u544a\u6309\u82f1\u96c4\u8054\u76df\u8d26\u53f7\u4fdd\u5b58/u)
  assert.doesNotMatch(zhCN, /\u8fd9\u91cc\u8bf4\u660e\u6bcf\u7c7b\u62a5\u544a\u662f\u4ec0\u4e48/u)
  assert.doesNotMatch(zhCN, /\u5df2\u63a5\u5165\u5165\u53e3|\u672c\u5730\u9636\u6bb5|\u89c4\u5212\u4e2d|\u4f7f\u7528\u4f4d\u7f6e/u)
  assert.doesNotMatch(zhCN, /'aiAnalysis\.[^']+': '[^']*(?:\u6570\u636e\u72b6\u6001|\u672c\u5730\u6218\u7ee9|\u5bf9\u5c40\u8be6\u60c5|\u6570\u636e\u8be6\u60c5|\u68c0\u67e5\u672c\u5730\u6570\u636e)/u)
  assert.doesNotMatch(zhCN, /'aiAnalysis\.[^']+': '[^']*(?:AI \u670d\u52a1|\u5f53\u524d\u9636\u6bb5|\u672a\u63a5\u5165\u771f\u5b9e\u6a21\u578b)/u)
  assert.doesNotMatch(zhCN, /\u53ef\u5206\u4eab|\u5468\u62a5\u6708\u62a5/u)
  assert.doesNotMatch(zhCN, /\u5386\u53f2\u62a5\u544a\u4e2d\u5fc3/u)
  assert.equal(existsSync(iconPath), true)

  const svg = readFileSync(iconPath, 'utf8')
  assert.match(svg, /fill="none"/)
  assert.match(svg, /stroke="currentColor"/)
  assert.match(svg, /stroke-linecap="round"/)
  assert.match(svg, /stroke-linejoin="round"/)
})

test('AI report center feature cards keep titles, positioning copy, and short tags', () => {
  const source = readViewSource()

  assert.match(source, /featureCards = computed<FeatureCard\[\]>/)
  assert.match(source, /t\('aiAnalysis\.featurePreGame'\)[\s\S]*t\('aiAnalysis\.featurePostGame'\)[\s\S]*t\('aiAnalysis\.featurePraise'\)[\s\S]*t\('aiAnalysis\.featureCoach'\)/)
  assert.match(source, /t\('aiAnalysis\.preGamePositioning'\)[\s\S]*t\('aiAnalysis\.postGamePositioning'\)[\s\S]*t\('aiAnalysis\.praisePositioning'\)[\s\S]*t\('aiAnalysis\.coachPositioning'\)/)
  assert.match(source, /class="feature-positioning"[\s\S]*card\.positioning/)
  assert.match(source, /t\('aiAnalysis\.tagTeammates'\)[\s\S]*t\('aiAnalysis\.tagRiskTips'\)[\s\S]*t\('aiAnalysis\.tagOpponentThreat'\)/)
  assert.match(source, /t\('aiAnalysis\.tagFromStrongToWeak'\)[\s\S]*t\('aiAnalysis\.tagSingleGameReview'\)/)
  assert.match(source, /t\('aiAnalysis\.tagPraise'\)[\s\S]*t\('aiAnalysis\.tagEmotionalValue'\)[\s\S]*t\('aiAnalysis\.tagEntertainment'\)/)
  assert.match(source, /t\('aiAnalysis\.tagRecent20'\)[\s\S]*t\('aiAnalysis\.tagChampionPool'\)/)
  assert.doesNotMatch(source, /description:|card\.description/)
  assert.doesNotMatch(source, /t\('aiAnalysis\.preGameDescription'\)|t\('aiAnalysis\.postGameDescription'\)|t\('aiAnalysis\.praiseDescription'\)|t\('aiAnalysis\.coachDescription'\)/)
  assert.doesNotMatch(source, /t\('aiAnalysis\.tagShareable'\)|t\('aiAnalysis\.tagWeeklyMonthly'\)/)
  assert.doesNotMatch(source, /t\('aiAnalysis\.featureTitle'\)|AI 功能入口|AI Feature Entrances/)
  assert.doesNotMatch(source, /feature-status|statusLabel|feature-usage|usageLabel/)
  assert.doesNotMatch(source, /useRouter|router\.push|openFeatureCard|routeName/)
  assert.doesNotMatch(source, /goMatchHistory|goLiveGame|viewReports/)
})

test('AI report center hero keeps account values and recharge as a UI-only placeholder', () => {
  const source = readViewSource()

  assert.doesNotMatch(source, /centerEyebrow|class="eyebrow"|\u5386\u53f2\u62a5\u544a\u4e2d\u5fc3/u)
  assert.match(source, /account-showcase-card/)
  assert.match(source, /rankpeek-account-value/)
  assert.match(source, /league-account-showcase/)
  assert.match(source, /balance-showcase/)
  assert.match(source, /balance-row/)
  assert.match(source, /balance-recharge-button/)
  assert.match(source, /rankpeekAccountLabel/)
  assert.match(source, /rankpeekBalanceLabel/)
  assert.match(source, /t\('aiAnalysis\.recharge'\)/)
  assert.match(source, /currentSummonerProfileIconUrl/)
  assert.match(source, /getProfileIconUrl\(summoner\.profileIconId\)/)
  assert.match(source, /@error="markAssetLoadFailed"/)
  assert.match(source, /accountStatusLabel = computed\(\(\) => currentSummonerName\.value \|\| t\('aiAnalysis\.noAccountStatus'\)\)/)
  assert.match(source, /rankpeekBalanceLabel = computed\(\(\) => '\uffe50\.00'\)/u)
  assert.doesNotMatch(source, /pay|payment|stripe|checkout|invoice|rechargeApi|balanceApi/i)
  assert.doesNotMatch(source, /account-report-note|accountReportHint|noAccountReportHint/)
})

test('AI report center history section keeps account tabs and report cards without the fun filter tab', () => {
  const source = readViewSource()

  assert.match(source, /selectedReportType = ref<ReportTypeFilter>\('all'\)/)
  assert.match(source, /reportTypeTabs = computed/)
  assert.match(source, /filteredAnalysisResults = computed/)
  assert.match(source, /getReportCategory/)
  assert.match(source, /getReportCategoryLabel/)
  assert.match(source, /getReportTitle/)
  assert.match(source, /getReportScopeLabel/)
  assert.doesNotMatch(source, /t\('aiAnalysis\.historyScopeHint'\)|localReportCountLabel/)
  assert.match(source, /t\('aiAnalysis\.filterAll'\)/)
  assert.match(source, /t\('aiAnalysis\.featurePreGame'\)/)
  assert.match(source, /t\('aiAnalysis\.featurePostGame'\)/)
  assert.match(source, /t\('aiAnalysis\.featurePraise'\)/)
  assert.match(source, /t\('aiAnalysis\.featureCoach'\)/)
  assert.doesNotMatch(source, /\{\s*key:\s*'fun'[\s\S]{0,120}label:\s*t\('aiAnalysis\.featureFun'\)/)
  assert.match(source, /case 'fun':\s*return t\('aiAnalysis\.featureFun'\)/)
  assert.match(source, /v-for="tab in reportTypeTabs"/)
  assert.match(source, /filteredAnalysisResults/)
  assert.match(source, /result\.output\.highlights\.slice\(0,\s*3\)/)
  assert.match(source, /getReportTitle\(result\)/)
  assert.match(source, /getReportScopeLabel\(result\)/)
  assert.match(source, /currentSummonerName \|\| t\('aiAnalysis\.currentAccountFallback'\)/)
  assert.match(source, /result\.matchId \? t\('aiAnalysis\.singleMatchReport'\) : t\('aiAnalysis\.accountReport'\)/)
  assert.match(source, /result\.createdAtLabel/)
})

test('AI report center no longer renders data status or AI service support cards', () => {
  const source = readViewSource()

  assert.doesNotMatch(source, /support-grid|data-status-card|service-status-card/)
  assert.doesNotMatch(source, /t\('aiAnalysis\.dataPrepTitle'\)|t\('aiAnalysis\.localMatches'\)|t\('aiAnalysis\.localDetails'\)|t\('aiAnalysis\.dataPrepStatus'\)/)
  assert.doesNotMatch(source, /t\('aiAnalysis\.checkLocalData'\)|t\('aiAnalysis\.checkingData'\)|t\('aiAnalysis\.inputHash'\)/)
  assert.doesNotMatch(source, /t\('aiAnalysis\.serverAiTitle'\)|t\('aiAnalysis\.serverAiPhase'\)|serverAiStatusLabel|serverAiPhaseLabel|isServerAiEnabled/)
  assert.doesNotMatch(source, /class="secondary-action prep-action"|class="data-detail-line"|service-stage|prep-grid|prep-body/)
})

test('AI analysis history renders report cards that promote report content over engineering metadata', () => {
  const source = readViewSource()

  assert.match(source, /t\('aiAnalysis\.emptyHistoryTitle'\)/)
  assert.match(source, /t\('aiAnalysis\.emptyHistoryBody'\)/)
  assert.match(source, /report-card/)
  assert.match(source, /getReportTitle\(result\)/)
  assert.match(source, /result\.output\.summary/)
  assert.match(source, /result\.createdAtLabel/)
  assert.match(source, /getReportCategoryLabel\(result\)/)
  assert.match(source, /report-meta/)
  assert.match(source, /result\.subjectKey/)
  assert.match(source, /result\.gameVersion/)
  assert.match(source, /result\.modelName/)
  assert.doesNotMatch(source, /result\.inputHash/)
  assert.doesNotMatch(source, /class="type-code"/)
  assert.ok(source.indexOf('report-main') < source.indexOf('report-meta'))
})
