import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('uses a vertical-first team layout with analysis actions above the teams', () => {
  const source = readFileSync(new URL('./GamingView.vue', import.meta.url), 'utf8')
  const toolbarIndex = source.indexOf("'match-analysis-toolbar'")
  const teamsIndex = source.indexOf('class="teams-container"')

  assert.match(source, /class="team-panel team-blue"/)
  assert.match(source, /class="team-panel team-red"/)
  assert.match(source, /'match-analysis-toolbar'/)
  assert.doesNotMatch(source, /data-watermark="RANKPEEK AI"/)
  assert.match(source, /class="ai-wordmark"/)
  assert.match(source, /viewBox="0 0 1240 220"/)
  assert.match(source, />RANKPEEK</)
  assert.match(source, />AI</)
  assert.match(source, /class="wordmark-echo wordmark-ai-echo" x="970"/)
  assert.match(source, /class="wordmark-main wordmark-ai" x="960"/)
  assert.match(source, />队友成分</)
  assert.match(source, />赛前分析</)
  assert.match(source, />检查大腿or拖油瓶</)
  assert.match(source, />分析小代or软柿子</)
  assert.match(source, /class="analysis-help"/)
  assert.match(source, /class="\['match-analysis-toolbar', \{ 'has-analysis-output': latestAnalysisSummary \}\]"/)
  assert.match(source, /class="analysis-actions"/)
  assert.match(source, /v-if="latestAnalysisSummary"/)
  assert.match(source, /class="analysis-result"/)
  assert.match(source, /latestAnalysisSummary/)
  assert.match(source, /\.match-analysis-toolbar\s*{[\s\S]*align-items:\s*center;[\s\S]*min-height:\s*142px;[\s\S]*max-height:\s*142px;/)
  assert.match(source, /\.ai-wordmark\s*{[\s\S]*height:\s*clamp\(170px, 24vw, 300px\);/)
  assert.match(source, /\.ai-wordmark\s*{[\s\S]*z-index:\s*0;/)
  assert.match(source, /\.match-analysis-toolbar\.has-analysis-output\s*{[\s\S]*max-height:\s*360px;/)
  assert.match(source, /\.analysis-result\s*{[\s\S]*margin-top:\s*18px;/)
  assert.match(source, /\.analysis-actions\s*{[\s\S]*justify-content:\s*flex-start;/)
  assert.match(source, /\.analysis-action\s*{[\s\S]*flex:\s*0 1 220px;[\s\S]*min-width:\s*178px;/)
  assert.match(source, /\.analysis-btn\s*{[\s\S]*justify-content:\s*flex-start;[\s\S]*min-height:\s*84px;[\s\S]*font-size:\s*28px;[\s\S]*line-height:\s*1;[\s\S]*text-align:\s*left;/)
  assert.match(source, /\.analysis-btn::before[\s\S]*linear-gradient\(120deg/)
  assert.match(source, /\.analysis-action:hover \.analysis-btn[\s\S]*translateY\(-2px\)/)
  assert.match(source, /@media \(max-width:\s*720px\)[\s\S]*\.match-analysis-toolbar\s*{[\s\S]*align-items:\s*center;[\s\S]*\.analysis-btn\s*{[\s\S]*min-height:\s*76px;[\s\S]*font-size:\s*24px;/)
  assert.doesNotMatch(source, />队友成分分析</)
  assert.doesNotMatch(source, />BP 前分析</)
  assert.doesNotMatch(source, />BP 后分析</)
  assert.equal(toolbarIndex > -1 && teamsIndex > -1 && toolbarIndex < teamsIndex, true)
  assert.match(source, /\.teams-container\s*{\s*display:\s*grid;[\s\S]*grid-template-columns:\s*1fr;/)
  assert.match(source, /@media \(min-width:\s*1180px\)[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/)
})
