import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('match history card renders spell loadout, mode-aware traits, and performance tags', () => {
  const source = readFileSync(new URL('./MatchHistoryCard.vue', import.meta.url), 'utf8')
  const apiTypes = readFileSync(new URL('../../types/api.ts', import.meta.url), 'utf8')

  assert.match(source, /getSummonerSpellIconUrl/)
  assert.match(source, /getPerkIconUrl/)
  assert.match(source, /getAugmentIconUrl/)
  assert.match(source, /getItemAssetDetails/)
  assert.match(source, /getPerkAssetDetails/)
  assert.match(source, /getAugmentAssetDetails/)
  assert.match(source, /getMatchPerformanceTags/)
  assert.match(source, /const currentSpellSlots = computed/)
  assert.match(source, /const currentTraitMode = computed<MatchTraitMode>/)
  assert.match(source, /hasValidAugment\(currentPlayer\.value\) \? 'augment' : 'perk'/)
  assert.match(source, /const currentTraitSlots = computed\(\(\) => getTraitSlots\(currentPlayer\.value\)\)/)
  assert.match(source, /spell1Id/)
  assert.match(source, /spell2Id/)
  assert.doesNotMatch(source, /getPerkSlots\(currentPlayer\.value, 1\)/)
  assert.doesNotMatch(source, /getAugmentSlots\(currentPlayer\.value, 2\)/)
  assert.doesNotMatch(source, /'perk0', 'perk1', 'perk2', 'perk3', 'perk4', 'perk5'/)
  assert.match(source, /function getTraitSlots/)
  assert.match(source, /function buildPerkTraitSlots/)
  assert.match(source, /function buildAugmentTraitSlots/)
  assert.match(source, /createTraitSlot\('perk', 0, primaryId\)/)
  assert.match(source, /createTraitSlot\('perk', 1, secondaryId\)/)
  assert.match(source, /kind === 'augment'\s*\?\s*getAugmentIconUrl\(id\)\s*:\s*getPerkIconUrl\(id\)/)
  assert.match(source, /readTraitId\(statsRecord, participantRecord, 'perk0'\)/)
  assert.match(source, /readTraitId\(statsRecord, participantRecord, 'perkSubStyle'\)/)
  assert.match(source, /readTraitId\(statsRecord, participantRecord, 'perkPrimaryStyle'\)/)
  assert.match(source, /readTraitId\(statsRecord, participantRecord, 'perk5'\)/)
  assert.match(source, /Array\.from\(\{ length: 6 \}/)
  assert.match(source, /playerAugment1/)
  assert.match(source, /playerAugment6/)
  assert.match(source, /extraFields/)
  assert.match(source, /participant\?\.stats/)
  assert.match(source, /v-for="slot in currentSpellSlots"/)
  assert.match(source, /currentTraitMode === 'augment' \? 'trait-grid' : 'trait-column'/)
  assert.match(source, /v-for="slot in currentTraitSlots"/)
  assert.match(source, /class="loadout-slot trait-slot"/)
  assert.match(source, /\{ empty: slot\.empty \}/)
  assert.match(source, /:title="slot\.label"/)
  assert.match(source, /\.trait-grid/)
  assert.match(source, /--loadout-slot-size: 19px/)
  assert.match(source, /grid-template-columns: repeat\(3, var\(--loadout-slot-size\)\)/)
  assert.match(source, /\.trait-slot\.loadout-slot-perk/)
  assert.match(source, /--loadout-slot-size: 17px/)
  assert.match(source, /class="performance-tags"/)
  assert.match(source, /v-for="tag in performanceTags"/)
  assert.match(source, /\{\{ tag\.label \}\}/)
  assert.match(source, /@error="markAssetLoadFailed"/)
  assert.match(apiTypes, /^\s*playerAugment1\?: number/m)
  assert.match(apiTypes, /^\s*playerAugment5\?: number/m)
  assert.match(apiTypes, /^\s*playerAugment6\?: number/m)
})

test('match history card exposes inline detail expanded state and chevron affordance', () => {
  const source = readFileSync(new URL('./MatchHistoryCard.vue', import.meta.url), 'utf8')

  assert.match(source, /expanded\?: boolean/)
  assert.match(source, /expanded: false/)
  assert.match(source, /:class="\{ win: isWin, loss: !isWin, expanded \}"/)
  assert.match(source, /class="detail-chevron"/)
  assert.match(source, /:class="\{ expanded \}"/)
  assert.match(source, /:aria-expanded="expanded"/)
  assert.match(source, /@click\.stop="emit\('open-detail', match\)"/)
  assert.match(source, /class="chevron-icon"/)
})
