import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('shows client-style match detail tabs, safe assets, and navigable player rows', () => {
  const source = readFileSync(new URL('./MatchDetailModal.vue', import.meta.url), 'utf8')

  assert.match(source, /import UserTagBadgeList from '@\/components\/summoner\/UserTagBadgeList\.vue'/)
  assert.match(source, /from '@\/utils\/matchDetailMetrics'/)
  assert.match(source, /from '@\/utils\/gameAssetUrls'/)
  assert.match(source, /h\(UserTagBadgeList/)
  assert.match(source, /recordStatus: getPlayerSummary\(componentProps\.player\)\?\.recordStatus/)
  assert.match(source, /tags: getPlayerSummary\(componentProps\.player\)\?\.tag/)
  assert.doesNotMatch(source, /limit:\s*2/)
  assert.match(source, /class="match-hero"/)
  assert.match(source, /class="detail-tabs"/)
  assert.match(source, /activeTab/)
  assert.match(source, /key: 'overview'/)
  assert.match(source, /key: 'damage'/)
  assert.match(source, /key: 'economy'/)
  assert.match(source, /key: 'vision'/)
  assert.match(source, /key: 'items'/)
  assert.match(source, /t\('matchDetail\.overviewTab'\)/)
  assert.match(source, /t\('matchDetail\.damageTab'\)/)
  assert.match(source, /t\('matchDetail\.economyTab'\)/)
  assert.match(source, /t\('matchDetail\.visionTab'\)/)
  assert.match(source, /t\('matchDetail\.itemsTab'\)/)
  assert.match(source, /const blueTeamTotals = computed/)
  assert.match(source, /const redTeamTotals = computed/)
  assert.match(source, /const allPlayers = computed/)
  assert.match(source, /function getPlayerItemSlots/)
  assert.match(source, /getItemIconSlots/)
  assert.match(source, /getSummonerSpellIconUrl/)
  assert.match(source, /getPerkIconUrl/)
  assert.match(source, /markAssetLoadFailed/)
  assert.match(source, /class="player-build"/)
  assert.match(source, /class="item-slot"/)
  assert.match(source, /@error="markAssetLoadFailed"/)
  assert.match(source, /@click="handlePlayerClick\(player\)"/)
  assert.match(source, /emit\('navigateToPlayer', player\.gameName, player\.tagLine\)/)
  assert.match(source, /v-for="player in blueTeamPlayers"/)
  assert.match(source, /v-for="player in redTeamPlayers"/)
  assert.doesNotMatch(source, /fetch\(|axios|apiClient|DeepSeek|Kimi|OpenAI|saveAnalysisResult|saveServerAiStream/i)
  assert.doesNotMatch(source, /ai-review|aiReview|comingSoon/i)
  assert.doesNotMatch(source, /timeline-chart|goldCurve|keyDeath|objectiveSetup/i)
  assert.doesNotMatch(source, /class="player-analysis"/)
})

test('renders match-history fallback while game detail is loading or failed', () => {
  const source = readFileSync(new URL('./MatchDetailModal.vue', import.meta.url), 'utf8')

  assert.doesNotMatch(source, /visible && gameDetail && matchHistory/)
  assert.match(source, /detailStatus\?: 'idle' \| 'loading' \| 'loaded' \| 'error'/)
  assert.match(source, /const displayGameDetail = computed<GameDetail \| null>/)
  assert.match(source, /mergeGameDetailWithSummary\(detail, fallbackGameDetail\.value\)/)
  assert.match(source, /function toGameDetailFromMatchHistory\(match: MatchHistory \| null\): GameDetail \| null/)
  assert.match(source, /function mergeGameStatsWithSummary\(stats: GameStats, summaryStats\?: GameStats\): GameStats/)
  assert.match(source, /challenges: stats\.challenges \|\| summaryStats\.challenges/)
  assert.match(source, /fillPositiveSummaryStats\(merged, summaryStats\)/)
  assert.match(source, /class="detail-load-state"/)
  assert.match(source, /t\('matchDetail\.loadingFallback'\)/)
  assert.match(source, /t\('matchDetail\.failedFallback'\)/)
})

test('match detail hero shows loadout icons and performance tags from detail or fallback data', () => {
  const source = readFileSync(new URL('./MatchDetailModal.vue', import.meta.url), 'utf8')

  assert.match(source, /getMatchPerformanceTags/)
  assert.match(source, /getAugmentIconUrl/)
  assert.match(source, /const myPerformanceTags = computed/)
  assert.match(source, /const mySpellSlots = computed/)
  assert.match(source, /const myPerkSlots = computed/)
  assert.match(source, /const myAugmentSlots = computed/)
  assert.match(source, /class="hero-loadout-stack"/)
  assert.match(source, /v-for="slot in mySpellSlots"/)
  assert.match(source, /v-for="slot in myPerkSlots"/)
  assert.match(source, /v-for="slot in myAugmentSlots"/)
  assert.match(source, /class="performance-tags hero-tags"/)
  assert.match(source, /v-for="tag in myPerformanceTags"/)
  assert.match(source, /playerAugment1: stats\?\.playerAugment1/)
  assert.match(source, /perk0: stats\?\.perk0/)
  assert.match(source, /doubleKills: stats\?\.doubleKills/)
  assert.match(source, /largestKillingSpree: stats\?\.largestKillingSpree/)
})
