import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

test('OP.GG champion panel renders reusable loading, success, error, and empty states', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /v-if="loading"/)
  assert.match(source, /v-else-if="error"/)
  assert.match(source, /v-else-if="!detail"/)
  assert.match(source, /v-else/)
  assert.match(source, /@click="\$emit\('retry'\)"/)
  assert.doesNotMatch(source, /opgg-modal-overlay/)
  assert.doesNotMatch(source, /aria-modal="true"/)
})

test('OP.GG champion panel keeps the existing core stats and build sections', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /formatPercent\(detail\.stats\.winRate\)/)
  assert.match(source, /formatPercent\(detail\.stats\.pickRate\)/)
  assert.match(source, /formatPercent\(detail\.stats\.banRate\)/)
  assert.match(source, /formatNumber\(detail\.stats\.kda\)/)
  assert.match(source, /summonerSpells/)
  assert.match(source, /augments/)
  assert.match(source, /runes/)
  assert.match(source, /skillOrders/)
  assert.match(source, /starterItems/)
  assert.match(source, /boots/)
  assert.match(source, /coreItems/)
  assert.match(source, /lastItems/)
  assert.match(source, /第四\/五\/六件装备/)
  assert.match(source, /getIconUrl\(section\.iconType, id\)/)
  assert.match(source, /getAugmentIconUrl/)
  assert.match(source, /if \(iconType === 'augment'\) return getAugmentIconUrl\(id\)/)
})

test('OP.GG champion panel only shows augment sections for arena mode', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')
  const buildSections = source.match(/const buildSections = computed<BuildSection\[\]>\(\(\) => \{[\s\S]*?\n\}\)/)?.[0] || ''

  assert.match(buildSections, /if \(detail\.mode === 'arena'\)/)
  assert.match(buildSections, /sections\.push\(\{ key: 'augments'/)
})

test('OP.GG champion panel reuses rich asset tooltips for rune and item icons', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')
  const lastItemsBlock = source.match(/<div v-if="isLastItemsSection\(section\) && section\.options\.length"[\s\S]*?<div v-else-if="section\.options\.length"/)?.[0] || ''
  const runeTemplate = source.match(/<div v-if="section\.key === 'runes'"[\s\S]*?<div v-else-if="section\.key === 'skillOrders'"/)?.[0] || ''
  const itemBuildBlock = source.match(/<div v-else class="opgg-icon-chain">[\s\S]*?<div v-if="section\.key !== 'runes'"/)?.[0] || ''

  assert.match(source, /import AssetHoverTooltip from '@\/components\/common\/AssetHoverTooltip\.vue'/)
  assert.match(source, /type GameAssetTooltipDetails/)
  assert.match(source, /getItemTooltipDetails/)
  assert.match(source, /getPerkTooltipDetails/)
  assert.match(source, /function getOpggTooltipDetails\(iconType: IconType, id: number\): GameAssetTooltipDetails \| null/)
  assert.match(source, /if \(iconType === 'perk'\) return getPerkTooltipDetails\(id\)/)
  assert.match(source, /if \(iconType === 'item'\) return getItemTooltipDetails\(id\)/)
  assert.match(lastItemsBlock, /<AssetHoverTooltip[\s\S]*getOpggTooltipDetails\(section\.iconType, id\)!/)
  assert.match(runeTemplate, /<AssetHoverTooltip[\s\S]*getOpggTooltipDetails\(section\.iconType, slot\.id\)!/)
  assert.match(itemBuildBlock, /<AssetHoverTooltip[\s\S]*getOpggTooltipDetails\(section\.iconType, id\)!/)
  assert.match(source, /\.opgg-icon-slot\s+:deep\(\.asset-tooltip-trigger\)\s*\{[\s\S]*width:\s*100%;[\s\S]*height:\s*100%;/)
})

test('OP.GG champion panel shows counter champion icons in the detail header', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /counters\?: OpggChampionCounter\[\]/)
  assert.match(source, /counterChampions/)
  assert.match(source, /劣势对位/)
  assert.match(source, /class="opgg-counter-strip"/)
  assert.match(source, /getChampionIconUrl\(counter\.championId\)/)
})

test('OP.GG champion panel can show the back button inline with the detail title', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /showBackButton\?: boolean/)
  assert.match(source, /back: \[\]/)
  assert.match(source, /opgg-title-heading/)
  assert.match(source, /opgg-inline-back-btn/)
  assert.match(source, /v-if="showBackButton"/)
  assert.match(source, /@click="\$emit\('back'\)"/)
})

test('OP.GG champion panel can render the selected champion name as the detail title', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /title\?: string/)
  assert.match(source, /const panelTitle = computed/)
  assert.match(source, /props\.title\?\.trim\(\)/)
  assert.match(source, /props\.detail\?\.championName/)
  assert.match(source, /<h2 id="opgg-panel-title">\{\{ panelTitle \}\}<\/h2>/)
  assert.doesNotMatch(source, /<h2 id="opgg-panel-title">OP\.GG<\/h2>/)
})

test('OP.GG champion panel limits build rows to two until expanded', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /INITIAL_VISIBLE_BUILD_OPTIONS = 2/)
  assert.match(source, /visibleSectionOptions\(section\)/)
  assert.match(source, /section\.options\.slice\(0, INITIAL_VISIBLE_BUILD_OPTIONS\)/)
  assert.match(source, /@click="toggleSectionExpandedFromCard\(section\)"/)
  assert.match(source, /@keydown\.enter\.prevent="toggleSectionExpandedFromCard\(section\)"/)
  assert.match(source, /@keydown\.space\.prevent="toggleSectionExpandedFromCard\(section\)"/)
  assert.match(source, /:aria-expanded="canExpandSection\(section\) \? isSectionExpanded\(section\.key\) : undefined"/)
  assert.match(source, /opgg-section-expand-indicator/)
  assert.doesNotMatch(source, /<button[\s\S]*opgg-section-toggle/)
})

test('OP.GG champion panel renders fourth fifth and sixth items as three columns', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /LAST_ITEM_COLUMN_SIZE = 5/)
  assert.match(source, /LAST_ITEM_COLLAPSED_OPTIONS_PER_COLUMN = 2/)
  assert.match(source, /LAST_ITEM_COLUMN_TITLES = \['第四件装备', '第五件装备', '第六件装备'\]/)
  assert.match(source, /function lastItemColumns\(section: BuildSection\)/)
  assert.match(source, /section\.options\.slice\(start, start \+ LAST_ITEM_COLUMN_SIZE\)/)
  assert.match(source, /function visibleLastItemColumnOptions/)
  assert.match(source, /class="opgg-last-items-grid"/)
  assert.match(source, /class="opgg-last-item-column"/)
  assert.match(source, /class="opgg-last-item-list"/)
  assert.match(source, /class="opgg-last-item-metrics"/)
  assert.match(source, /formatPercent\(option\.winRate\)/)
  assert.match(source, /formatLastItemGames\(option\.games\)/)
  assert.doesNotMatch(source, /section\.key === 'lastItems'[\s\S]*opgg-build-list/)
})

test('OP.GG champion panel moves rune metrics to the board and names stat shards without values', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')
  const runeTemplate = source.match(/<div v-if="section\.key === 'runes'"[\s\S]*?<div v-else-if="section\.key === 'skillOrders'"/)?.[0] || ''
  const runeStyles = source.match(/\.opgg-rune-board \{[\s\S]*?\.opgg-skill-order \{/)?.[0] || ''

  assert.match(source, /splitOpggRuneIds/)
  assert.match(source, /section\.key === 'runes'/)
  assert.match(source, /selectedRuneOption\(section\)/)
  assert.match(source, /selectRuneOption/)
  assert.match(source, /runeTreeRows/)
  assert.match(source, /runeStatRows/)
  assert.match(source, /class="opgg-rune-groups"/)
  assert.match(source, /class="opgg-rune-board"/)
  assert.match(source, /class="opgg-rune-tabs"/)
  assert.match(source, /class="opgg-rune-tab"/)
  assert.match(source, /class="opgg-rune-tab-icons"/)
  assert.doesNotMatch(source, /opgg-rune-tab-metrics/)
  assert.doesNotMatch(source, /opgg-rune-tab-metric/)
  assert.doesNotMatch(source, /formatPercent\(runeOption\.pickRate\)/)
  assert.doesNotMatch(source, /formatPercent\(runeOption\.winRate\)/)
  assert.doesNotMatch(source, /formatRuneTabGames\(runeOption\.games\)/)
  assert.match(source, /class="opgg-rune-board-grid"/)
  assert.match(source, /class="opgg-rune-tree opgg-rune-tree-primary"/)
  assert.match(source, /class="opgg-rune-tree opgg-rune-tree-secondary"/)
  assert.match(source, /class="opgg-rune-row-grid"/)
  assert.match(source, /class="opgg-icon-slot opgg-rune-slot"/)
  assert.match(source, /muted: !slot\.selected/)
  assert.doesNotMatch(source, /opgg-rune-placeholder/)
  assert.match(source, /class="opgg-rune-shards"/)
  assert.match(source, /class="opgg-rune-shard-row"/)
  assert.match(source, /class="opgg-rune-shard-label"/)
  assert.match(source, /runeStatLabel\(slot\.id\)/)
  assert.match(source, /getPerkAssetDetails/)
  assert.match(source, /class="opgg-rune-keystone-summary"/)
  assert.match(source, /runeKeystoneName\(option\)/)
  assert.match(runeTemplate, /opgg-rune-keystone-summary[\s\S]*runeKeystoneName\(option\)[\s\S]*胜率[\s\S]*formatPercent\(option\.winRate\)/)
  assert.match(source, /class="opgg-rune-board-metrics"/)
  assert.doesNotMatch(source, /class="opgg-rune-board-metric opgg-rune-board-win"/)
  assert.match(source, /class="opgg-rune-board-metric opgg-rune-board-pick"/)
  assert.match(source, /class="opgg-rune-board-metric opgg-rune-board-games"/)
  assert.match(source, /formatPercent\(option\.winRate\)/)
  assert.match(source, /formatPercent\(option\.pickRate\)/)
  assert.match(source, /formatRuneTabGames\(option\.games\)/)
  assert.doesNotMatch(runeTemplate, /opgg-rune-page-icon/)
  assert.doesNotMatch(source, />主系</)
  assert.doesNotMatch(source, />主系天赋</)
  assert.doesNotMatch(source, />副系</)
  assert.doesNotMatch(source, />副系天赋</)
  assert.doesNotMatch(source, />小属性</)
  assert.match(runeTemplate, /v-if="slot\.id !== null"[\s\S]*getIconUrl\(section\.iconType, slot\.id\)/)
  assert.doesNotMatch(runeTemplate, /v-else[\s\S]*class="opgg-icon-slot opgg-rune-placeholder"/)
  assert.doesNotMatch(runeTemplate, /class="opgg-build-meta"/)
  assert.doesNotMatch(runeTemplate, /formatGameCount\(option\.games\)/)
  assert.match(source, /section\.key === 'runes'[\s\S]*return false/)
  assert.match(source, /const isKeystoneRow = includeKeystone && rowIndex === 0/)
  assert.match(source, /8100:\s*\[\s*\[\s*8112,\s*8128,\s*9923\s*\][\s\S]*\[\s*8126,\s*8139,\s*8143\s*\][\s\S]*\[\s*8137,\s*8140,\s*8141\s*\][\s\S]*\[\s*8135,\s*8105,\s*8106\s*\]/)
  assert.doesNotMatch(source, /8100:\s*\[[\s\S]*8124/)
  assert.doesNotMatch(source, /8100:\s*\[[\s\S]*8136/)
  assert.doesNotMatch(source, /8100:\s*\[[\s\S]*8120/)
  assert.doesNotMatch(source, /8100:\s*\[[\s\S]*8138/)
  assert.match(source, /8200:\s*\[\s*\[\s*8214,\s*8229,\s*8230,\s*8992\s*\]/)
  assert.match(source, /8300:\s*\[\s*\[\s*8351,\s*8360,\s*8369\s*\][\s\S]*\[\s*8306,\s*8304,\s*8321\s*\][\s\S]*\[\s*8313,\s*8352,\s*8345\s*\][\s\S]*\[\s*8347,\s*8410,\s*8316\s*\]/)
  assert.match(source, /const visibleRuneRowIds = isKeystoneRow[\s\S]*rowIds\.filter\(id => selectedSet\.has\(id\)\)[\s\S]*rowIds/)
  assert.match(source, /slots: visibleRuneRowIds\.map\(id => \(\{ id, selected: selectedSet\.has\(id\) \}\)\)/)
  assert.doesNotMatch(source, /const RUNE_STAT_LAYOUT/)
  assert.match(source, /5001:\s*'成长生命值'/)
  assert.match(source, /5002:\s*'护甲'/)
  assert.match(source, /5003:\s*'魔抗'/)
  assert.match(source, /5005:\s*'攻击速度'/)
  assert.match(source, /5007:\s*'技能急速'/)
  assert.match(source, /5008:\s*'适应之力'/)
  assert.match(source, /5010:\s*'移动速度'/)
  assert.match(source, /5011:\s*'固定生命值'/)
  assert.match(source, /5012:\s*'成长双抗'/)
  assert.match(source, /const RUNE_STAT_LABELS: Record<number, string> = \{[\s\S]*5007: '[^0-9']+'[\s\S]*5008: '[^0-9']+'[\s\S]*5012: '[^0-9']+'/)
  assert.doesNotMatch(source, /5007:\s*'[0-9]/)
  assert.doesNotMatch(source, /5008:\s*'[0-9]/)
  assert.doesNotMatch(source, /5012:\s*'[0-9]/)
  assert.match(source, /function runeStatRows\(selectedIds: number\[\]\): RuneShardRow\[\][\s\S]*selectedIds[\s\S]*filter\(id => Number\.isFinite\(id\) && id > 0\)[\s\S]*runeStatLabel\(id\)/)
  assert.doesNotMatch(source, /slots: rowIds\.map\(id => \(\{ id, selected: id === selectedId \}\)\)/)
  assert.match(runeStyles, /min-height:\s*196px/)
  assert.doesNotMatch(runeStyles, /\.opgg-rune-tab-metrics/)
  assert.doesNotMatch(runeStyles, /\.opgg-rune-tab-metric/)
  assert.match(runeStyles, /\.opgg-rune-board-grid \{[\s\S]*grid-template-columns:\s*max-content max-content max-content minmax\(96px,\s*1fr\)/)
  assert.match(runeStyles, /\.opgg-rune-board-grid \{[\s\S]*justify-content:\s*start/)
  assert.match(runeStyles, /\.opgg-rune-keystone-summary \{[\s\S]*display:\s*flex[\s\S]*align-items:\s*baseline/)
  assert.match(runeStyles, /\.opgg-rune-keystone-summary strong \{[\s\S]*font-size:\s*15px/)
  assert.match(runeStyles, /\.opgg-rune-tree-secondary \{[\s\S]*justify-items:\s*start/)
  assert.match(runeStyles, /\.opgg-rune-shards \{[\s\S]*justify-items:\s*start/)
  assert.match(runeStyles, /\.opgg-rune-shard-row \{[\s\S]*grid-template-columns:\s*28px max-content/)
  assert.match(runeStyles, /\.opgg-rune-shard-label \{[\s\S]*white-space:\s*nowrap/)
  assert.match(runeStyles, /\.opgg-rune-board-metrics \{[\s\S]*justify-items:\s*end/)
  assert.match(runeStyles, /\.opgg-rune-board-metric \{[\s\S]*justify-items:\s*end/)
  assert.match(runeStyles, /\.opgg-rune-board-metric \{[\s\S]*text-align:\s*right/)
  assert.match(runeStyles, /\.opgg-rune-board-metric strong \{[\s\S]*font-size:\s*16px/)
  assert.match(runeStyles, /\.opgg-rune-slot\.muted \{[\s\S]*opacity:\s*0\.56/)
  assert.match(runeStyles, /\.opgg-rune-slot\.muted img \{[\s\S]*filter:\s*grayscale\(1\)/)
  assert.doesNotMatch(runeStyles, /visibility:\s*hidden/)
})

test('OP.GG champion panel renders skill orders as QWER chips with detailed sequence', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /title: '技能点法'/)
  assert.match(source, /v-else-if="section\.key === 'skillOrders'"/)
  assert.match(source, /class="opgg-skill-order"/)
  assert.match(source, /class="opgg-skill-priority"/)
  assert.match(source, /class="opgg-skill-sequence"/)
  assert.match(source, /skillOrderSequence\(option\)/)
  assert.match(source, /skillChipClass\(id\)/)
  assert.match(source, /formatSkillId\(id\)/)
  assert.match(source, /opgg-skill-index/)
})

test('OP.GG champion panel keeps build row labels above their own values', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /opgg-build-meta-column/)
  assert.match(source, /opgg-build-pick/)
  assert.match(source, /opgg-build-win/)
  assert.match(source, /opgg-build-sample/)
  assert.match(source, /选择率/)
  assert.match(source, /胜率/)
  assert.match(source, /样本/)
  assert.match(source, /formatPercent\(option\.pickRate\)/)
  assert.match(source, /formatPercent\(option\.winRate\)/)
  assert.match(source, /formatGameCount\(option\.games\)/)
  assert.match(source, /align-self: center/)
  assert.match(source, /\.opgg-build-meta \{[\s\S]*white-space: nowrap/)
  assert.match(source, /\.opgg-build-meta \{[\s\S]*grid-template-columns:\s*repeat\(3,\s*max-content\)/)
  assert.match(source, /\.opgg-build-meta-column \{[\s\S]*display: grid/)
  assert.match(source, /\.opgg-build-meta-column \{[\s\S]*grid-template-rows: auto auto/)
  assert.match(source, /\.opgg-build-meta span \{[\s\S]*color: #38bdf8[\s\S]*font-size: 13px/)
  assert.match(source, /\.opgg-build-meta strong \{[\s\S]*color: var\(--text-primary\)[\s\S]*font-size: 17px/)
  assert.match(source, /\.opgg-build-sample em \{[\s\S]*position: static/)
  assert.doesNotMatch(source, /\.opgg-build-meta-column \{[\s\S]*align-items: baseline/)
})

test('OP.GG champion panel keeps detail cards and build rows compact at minimum width', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /\.opgg-panel \{[\s\S]*min-width:\s*0/)
  assert.match(source, /\.opgg-content \{[\s\S]*padding:\s*14px 16px 16px/)
  assert.match(source, /\.opgg-summary \{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(112px,\s*1fr\)\)/)
  assert.match(source, /\.opgg-build-row \{[\s\S]*gap:\s*8px[\s\S]*padding:\s*8px/)
  assert.match(source, /\.opgg-build-meta \{[\s\S]*min-width:\s*240px/)
  assert.match(source, /\.opgg-icon-slot \{[\s\S]*width:\s*28px[\s\S]*height:\s*28px/)
})

test('OP.GG champion panel keeps header stats and build rows on one line at narrow width', () => {
  const source = readFileSync(new URL('./OpggChampionPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /\.opgg-panel-header \{[\s\S]*flex-wrap:\s*nowrap/)
  assert.match(source, /\.opgg-summary \{[\s\S]*grid-template-columns:\s*repeat\(4, minmax\(112px,\s*1fr\)\)/)
  assert.match(source, /\.opgg-build-row \{[\s\S]*flex-wrap:\s*nowrap/)
  assert.match(source, /\.opgg-icon-chain \{[\s\S]*flex-wrap:\s*nowrap/)
  assert.match(source, /\.opgg-build-meta \{[\s\S]*display:\s*grid/)
  assert.doesNotMatch(source, /@media \(max-width: 720px\)[\s\S]*flex-direction:\s*column/)
  assert.doesNotMatch(source, /@media \(max-width: 720px\)[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0,\s*1fr\)\)/)
})
